#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import fileinput

i = 0
j = 0
soma= 0
Dicionario = {}
frequencia = {}
Lista = []


for line in fileinput.input():
        
    while j < len(line)-1: #percorre cada linha adicionando as letras na lista
        letra = line.upper()[j]
        if letra != ' ':
            Lista.append(letra)        
        j = j + 1
    j = 0


while j < len(Lista): #percorre a lista contando as letras
        letra = Lista[j]
        while i < len(Lista): 
            if  letra == Lista[i]: 
                soma = soma + 1
            i = i + 1
        Dicionario [letra] = soma
        soma = 0
        i = 0
        j = j + 1

for (letra, soma) in Dicionario.items(): #adiciona letra em correspondente soma
    if soma in frequencia:
        frequencia[soma].append(letra)
    else:
        frequencia[soma] = [letra]

for numero in sorted(frequencia,reverse=True): #mostra organizado, ordem decrescente
    print 'Letras que aparecem',numero,'vez(es) --', numero*100/len(Lista),'% cada letra'
    for letra in frequencia[numero]:
        print ' ', letra
